################################################################################################
# This code produces the discard estimates and length distributions ##########################
#For stocks and sampling domains where the number of samples and input data aligned with those in the national database, 
#the estimated numbers-at-length and discard rates generated by the new code matched the outputs from the current national estimation method.   
#### BUT STILL UNDER DEVELOPMENT!!!!##########################################################################################
dir_path <- file.path("model", awg)
if (!dir.exists(dir_path)) {
  dir.create(dir_path, recursive = TRUE)
}
# params
interested.spp <- "COD"
#get the necessary tables
RDBES_data <- read.csv ("data/RDBES_data_H1_filtered.csv")
message("RDBES data loaded.")


my_function <- function(data) {
  
  species1 <- unique(data$Species)
  
  data <- data |> dplyr::filter(Species == interested.spp)
  
  print(paste0("discard estimates for ", interested.spp))
  
  return(data)
}


disc_est <- my_function(RDBES_data)
write.csv(disc_est, file = file.path(dir_path, "disc.len.dist.csv"), row.names = FALSE)

message("discards estimated and saved in model folder")




